{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
{{- if .Values.image}}
    {{- if .Values.image.pullSecrets}}
      {{- if ne .Values.image.pullSecret "" }}
  - name: {{ .Values.image.pullSecret }}
      {{- end }}
    {{- end }}
{{- end }}
metadata:
  name: {{ template "sysdig.serviceAccountName" .}}
  labels:
    app: {{ template "sysdig.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
